#!/bin/env python3
"""
Example 4-2.
The numbers generated by random.random are supposed to be uniform between
0 and 1; that is, every value in the range should have the same
probability.  Generate 1000 numbers from random.random and plot their PMF
and CDF. Is the distribution uniform?
"""

import numpy
import thinkplot
import thinkstats2


numpy.random.seed(1)
s = numpy.random.random_sample(1000)

# PMF: probability mass function
s_pmf = thinkstats2.Pmf(s)

# plot PMF
thinkplot.Pmf(s_pmf)
thinkplot.Config(xlabel='random number', ylabel='PMF')
thinkplot.Save(root='metis_q3_ch4_ex2_rnd_pmf', formats=['png'])

# CDF: cummulative distribution function
s_cdf = thinkstats2.Cdf(s)

# plot CDF
thinkplot.Cdf(s_cdf)
thinkplot.Config(xlabel='random number', ylabel='CDF')
thinkplot.Save(root='metis_q3_ch4_ex2_rnd_cdf', formats=['png'])

# Result:
# Yes, the distribution is uniform as indicated by the diaganol line
# in the cdf plot.
